### ISSUE TITLE
LinkageError when KieScanner loads

### ISSUE THREAD

**Issue by DuncanDoyle** [jbossdemocentral/brms-coolstore-demo#76]
When the "brms-coolstore-demo" application is opened and the KieScanner is started, we receive the following LinkageError:

````
11:20:18,953 WARNING [com.vaadin.server.DefaultDeploymentConfiguration] (http-127.0.0.1:8080-3)
=================================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
To show debug window, add ?debug to your application URL.
=================================================================
11:20:19,153 WARN  [org.kie.scanner.embedder.MavenSettings] (http-127.0.0.1:8080-9) Environment variable M2_HOME is not set
11:20:19,433 WARN  [org.jboss.modules] (http-127.0.0.1:8080-9) Failed to define class org.eclipse.sisu.inject.DefaultRankingFunction$ServletVisitor in Module "deployment.brms-coolstore-demo.war:main" from Service Module Loader: java.lang.LinkageError: Failed to link org/eclipse/sisu/inject/DefaultRankingFunction$ServletVisitor (Module "deployment.brms-coolstore-demo.war:main" from Service Module Loader)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:487) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.Module.loadModuleClass(Module.java:568) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.eclipse.sisu.inject.DefaultRankingFunction.<clinit>(DefaultRankingFunction.java:40) [org.eclipse.sisu.inject-0.3.0.M1.jar:]
	at org.codehaus.plexus.DefaultPlexusContainer$DefaultsModule.configure(DefaultPlexusContainer.java:860) [org.eclipse.sisu.plexus-0.3.0.M1.jar:]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:253) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.spi.Elements.getElements(Elements.java:108) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.spi.Elements.getElements(Elements.java:99) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:75) [org.eclipse.sisu.inject-0.3.0.M1.jar:]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:253) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.spi.Elements.getElements(Elements.java:108) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:135) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.Guice.createInjector(Guice.java:96) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.Guice.createInjector(Guice.java:73) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at com.google.inject.Guice.createInjector(Guice.java:62) [sisu-guice-3.2.3-no_aop.jar:3.2.3]
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481) [org.eclipse.sisu.plexus-0.3.0.M1.jar:]
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206) [org.eclipse.sisu.plexus-0.3.0.M1.jar:]
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:168) [org.eclipse.sisu.plexus-0.3.0.M1.jar:]
	at org.kie.scanner.embedder.MavenEmbedderUtils.buildPlexusContainer(MavenEmbedderUtils.java:166) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.MavenEmbedderUtils.buildPlexusContainer(MavenEmbedderUtils.java:140) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.PlexusComponentProvider.<init>(PlexusComponentProvider.java:37) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.MavenEmbedderUtils.buildComponentProvider(MavenEmbedderUtils.java:56) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.MavenEmbedder.<init>(MavenEmbedder.java:85) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.MavenEmbedder.<init>(MavenEmbedder.java:79) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.MavenProjectLoader.newMavenEmbedder(MavenProjectLoader.java:66) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.MavenProjectLoader.parseMavenPom(MavenProjectLoader.java:53) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.embedder.MavenProjectLoader.parseMavenPom(MavenProjectLoader.java:49) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.MavenPomModelGenerator.parse(MavenPomModelGenerator.java:33) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.compiler.kproject.xml.PomModel$Parser.parse(PomModel.java:110) [drools-compiler-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.compiler.kie.builder.impl.AbstractKieModule.getPomModel(AbstractKieModule.java:427) [drools-compiler-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.compiler.kie.builder.impl.AbstractKieModule.getJarDependencies(AbstractKieModule.java:129) [drools-compiler-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.kie.scanner.MavenClassLoaderResolver.getClassLoader(MavenClassLoaderResolver.java:65) [kie-ci-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.compiler.kie.builder.impl.KieModuleKieProject.<init>(KieModuleKieProject.java:68) [drools-compiler-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:119) [drools-compiler-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:111) [drools-compiler-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	at com.redhat.coolstore.util.BRMSUtil.<init>(BRMSUtil.java:27) [classes:]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [rt.jar:1.8.0_101]
	at org.jboss.weld.introspector.jlr.WeldConstructorImpl.newInstance(WeldConstructorImpl.java:206) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:128) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean.createInstance(ManagedBean.java:340) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget.produce(ManagedBean.java:204) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:296) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:104) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:626) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:692) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:137) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:797) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:806) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.SessionBean$SessionBeanInjectionTarget$1.proceed(SessionBean.java:179) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.SessionBean$SessionBeanInjectionTarget.inject(SessionBean.java:176) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.as.weld.injection.WeldEEInjection.inject(WeldEEInjection.java:78) [jboss-as-weld-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:54) [jboss-as-weld-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.as.ee.component.ComponentInstantiatorInterceptor.processInvocation(ComponentInstantiatorInterceptor.java:76) [jboss-as-ee-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.as.weld.ejb.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:92) [jboss-as-weld-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) [jboss-as-ee-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:278) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:330) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:64) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.as.jpa.interceptor.SFSBPreCreateInterceptor.processInvocation(SFSBPreCreateInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:70) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.1.2.Final-redhat-1.jar:1.1.2.Final-redhat-1]
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:162) [jboss-as-ee-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.component.stateful.StatefulSessionComponent.constructComponentInstance(StatefulSessionComponent.java:148) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.component.stateful.StatefulSessionComponent.constructComponentInstance(StatefulSessionComponent.java:70) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:135) [jboss-as-ee-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.component.stateful.StatefulSessionComponent.constructComponentInstance(StatefulSessionComponent.java:143) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.component.stateful.StatefulSessionComponent.constructComponentInstance(StatefulSessionComponent.java:70) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:90) [jboss-as-ee-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.component.stateful.StatefulSessionComponent.createInstance(StatefulSessionComponent.java:133) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.component.stateful.StatefulSessionComponent.createInstance(StatefulSessionComponent.java:70) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.cache.TransactionAwareObjectFactory.createInstance(TransactionAwareObjectFactory.java:53) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.cache.impl.backing.NonPassivatingBackingCacheImpl.create(NonPassivatingBackingCacheImpl.java:104) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.cache.impl.backing.NonPassivatingBackingCacheImpl.create(NonPassivatingBackingCacheImpl.java:55) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.cache.spi.impl.AbstractCache.create(AbstractCache.java:53) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.cache.impl.SimpleCache.create(SimpleCache.java:69) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.cache.impl.SimpleCache.create(SimpleCache.java:40) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.ejb3.component.stateful.StatefulSessionComponent.createSession(StatefulSessionComponent.java:237) [jboss-as-ejb3-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.weld.ejb.StatefulSessionObjectReferenceImpl.<init>(StatefulSessionObjectReferenceImpl.java:71) [jboss-as-weld-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.as.weld.services.bootstrap.WeldEjbServices.resolveEjb(WeldEjbServices.java:60) [jboss-as-weld-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.weld.bean.SessionBean.createReference(SessionBean.java:411) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.<init>(EnterpriseBeanProxyMethodHandler.java:71) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.SessionBean.create(SessionBean.java:296) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:68) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:626) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:692) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:137) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:797) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:806) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1$1.proceed(ManagedBean.java:165) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1.work(ManagedBean.java:161) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$FixInjectionPoint.run(ManagedBean.java:135) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget.inject(ManagedBean.java:157) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:297) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.apache.deltaspike.core.util.context.ContextualStorage.createContextualInstance(ContextualStorage.java:117) [deltaspike-core-api-1.4.1.jar:1.4.1]
	at org.apache.deltaspike.core.util.context.AbstractContext.get(AbstractContext.java:129) [deltaspike-core-api-1.4.1.jar:1.4.1]
	at com.vaadin.cdi.internal.AbstractVaadinContext.get(AbstractVaadinContext.java:156) [vaadin-cdi-1.0.3.jar:1.0.3]
	at com.vaadin.cdi.internal.ContextWrapper.get(ContextWrapper.java:49) [vaadin-cdi-1.0.3.jar:1.0.3]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:626) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:692) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:137) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:797) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:806) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1$1.proceed(ManagedBean.java:165) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1.work(ManagedBean.java:161) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$FixInjectionPoint.run(ManagedBean.java:135) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget.inject(ManagedBean.java:157) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:297) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at com.vaadin.cdi.internal.UIContextual.create(UIContextual.java:85) [vaadin-cdi-1.0.3.jar:1.0.3]
	at org.apache.deltaspike.core.util.context.ContextualStorage.createContextualInstance(ContextualStorage.java:117) [deltaspike-core-api-1.4.1.jar:1.4.1]
	at org.apache.deltaspike.core.util.context.AbstractContext.get(AbstractContext.java:129) [deltaspike-core-api-1.4.1.jar:1.4.1]
	at com.vaadin.cdi.internal.AbstractVaadinContext.get(AbstractVaadinContext.java:156) [vaadin-cdi-1.0.3.jar:1.0.3]
	at com.vaadin.cdi.internal.ContextWrapper.get(ContextWrapper.java:49) [vaadin-cdi-1.0.3.jar:1.0.3]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:626) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:653) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at com.vaadin.cdi.CDIUIProvider.createInstance(CDIUIProvider.java:95) [vaadin-cdi-1.0.3.jar:1.0.3]
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:191) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.cdi.server.VaadinCDIServletService.handleRequest(VaadinCDIServletService.java:92) [vaadin-cdi-1.0.3.jar:1.0.3]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:370) [vaadin-server-7.7.2.jar:7.7.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:419) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:654) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: com/google/inject/servlet/ServletModuleTargetVisitor
	at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.8.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [rt.jar:1.8.0_101]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482) [jboss-modules.jar:1.3.7.Final-redhat-1]
	... 159 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.servlet.ServletModuleTargetVisitor from [Module "deployment.brms-coolstore-demo.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.7.Final-redhat-1]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.7.Final-redhat-1]
	... 163 more
````

**Comment by DuncanDoyle** [comment]
https://issues.jboss.org/browse/DROOLS-1091
