### ISSUE TITLE
java/javac version mismatch

### ISSUE THREAD

**Issue by rgupta1234** [jbossdemocentral/brms-coolstore-demo#82]
Getting:

It's a java/javac version issue, cant get it to work - it breaks when it tries to apply free shipping

 tried java 7 as well, oracle AND openjdk

 [root@rgupta brms-coolstore-demo]# java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
[root@rgupta brms-coolstore-demo]# javac -version
javac 1.8.0_111
[root@rgupta brms-coolstore-demo]#

   at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.redhat.coolstore.ShoppingCart.getCartItemTotal()D
    at com.redhat.coolstore.Rule_Total_Shopping_Cart_Items1388852409.defaultConsequence(Rule_Total_Shopping_Cart_Items1388852409.java:7)
    at com.redhat.coolstore.Rule_Total_Shopping_Cart_Items1388852409DefaultConsequenceInvokerGenerated.evaluate(Unknown Source)
    at com.redhat.coolstore.Rule_Total_Shopping_Cart_Items1388852409DefaultConsequenceInvoker.evaluate(Unknown Source)
    at org.drools.core.common.DefaultAgenda.fireActivation(DefaultAgenda.java:1087)

10:33:10,703 ERROR [org.jboss.as.ejb3.invocation] (default task-39) WFLYEJB0034: EJB Invocation failed on component ShoppingCartServiceImplBRMS for method public abstract void com.redhat.coolstore.service.ShoppingCartService.priceShoppingCart(com.redhat.coolstore.model.ShoppingCart): javax.ejb.EJBException: WFLYEJB0442: Unexpected Error
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:184)

**Comment by DuncanDoyle** [comment]
Yeah, it's broken. I can reproduce this. It has to do with a recent fix I pushed for our coolstore-microservice demo. Will fix ASAP. Thanks for reporting.

**Comment by rgupta1234** [comment]
Thanks, let me know when I should try

**Comment by DuncanDoyle** [comment]
Can you give it a try. I've updated the default coolstore KJAR that is provided with the demo to use the new domain model I introduced in the rules repository (which fixed an issue on our coolstore-microservice demo).

I've just merged it to master, so you need to fetch the changes and run the "init.sh" script again. If it doesn't work, feel free to re-open the issue.

**Comment by rgupta1234** [comment]
Thank you, all working!
