### ISSUE TITLE
Error with KieScanner

### ISSUE THREAD

**Issue by hucmaggie** [jbossdemocentral/brms-coolstore-demo#84]
Getting the following error from KieScanner:

09:50:09,598 INFO  [stdout] (default task-96) Starting KieScanner...
09:50:09,598 INFO  [stdout] (default task-96) 
09:50:09,600 INFO  [stdout] (default task-96) Started KieScanner sucessfully...
09:50:09,600 INFO  [stdout] (default task-96) 
09:50:20,457 ERROR [stderr] (Timer-2) Exception in thread "Timer-2" java.lang.IllegalArgumentException: Unable to instantiate service for Class 'org.drools.compiler.compiler.GuidedRuleTemplateProvider'
09:50:20,457 ERROR [stderr] (Timer-2) 	at org.kie.internal.utils.ServiceRegistryImpl.get(ServiceRegistryImpl.java:169)
09:50:20,457 ERROR [stderr] (Timer-2) 	at org.drools.compiler.compiler.GuidedRuleTemplateFactory.loadProvider(GuidedRuleTemplateFactory.java:39)
09:50:20,457 ERROR [stderr] (Timer-2) 	at org.drools.compiler.compiler.GuidedRuleTemplateFactory.getGuidedRuleTemplateProvider(GuidedRuleTemplateFactory.java:32)
09:50:20,457 ERROR [stderr] (Timer-2) 	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.templateToPackageDescr(KnowledgeBuilderImpl.java:503)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl$9.map(CompositeKnowledgeBuilderImpl.java:419)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.buildResource(CompositeKnowledgeBuilderImpl.java:322)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.buildPackageDescr(CompositeKnowledgeBuilderImpl.java:310)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.buildPackages(CompositeKnowledgeBuilderImpl.java:114)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:105)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.kie.builder.impl.AbstractKieModule.buildKnowledgePackages(AbstractKieModule.java:243)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.kie.builder.impl.AbstractKieProject.verify(AbstractKieProject.java:64)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildKieProject(KieBuilderImpl.java:230)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildKieModule(KieBuilderImpl.java:222)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.kie.scanner.KieRepositoryScannerImpl.build(KieRepositoryScannerImpl.java:221)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.kie.scanner.KieRepositoryScannerImpl.updateKieModule(KieRepositoryScannerImpl.java:315)
09:50:20,458 ERROR [stderr] (Timer-2) 	at org.kie.scanner.KieRepositoryScannerImpl.scanNow(KieRepositoryScannerImpl.java:298)
09:50:20,459 ERROR [stderr] (Timer-2) 	at org.kie.scanner.KieRepositoryScannerImpl$ScanTask.run(KieRepositoryScannerImpl.java:270)
09:50:20,459 ERROR [stderr] (Timer-2) 	at java.util.TimerThread.mainLoop(Timer.java:555)
09:50:20,459 ERROR [stderr] (Timer-2) 	at java.util.TimerThread.run(Timer.java:505)
09:50:20,459 ERROR [stderr] (Timer-2) Caused by: java.lang.IllegalArgumentException: Unable to instantiate 'org.drools.workbench.models.guided.template.backend.GuidedRuleTemplateProviderImpl'
09:50:20,459 ERROR [stderr] (Timer-2) 	at org.kie.internal.utils.ServiceRegistryImpl$ReflectionInstantiator.newInstance(ServiceRegistryImpl.java:273)
09:50:20,459 ERROR [stderr] (Timer-2) 	at org.kie.internal.utils.ServiceRegistryImpl$ReflectionInstantiator.call(ServiceRegistryImpl.java:265)
09:50:20,459 ERROR [stderr] (Timer-2) 	at org.kie.internal.utils.ServiceRegistryImpl.get(ServiceRegistryImpl.java:167)
09:50:20,459 ERROR [stderr] (Timer-2) 	... 18 more
09:50:20,459 ERROR [stderr] (Timer-2) Caused by: java.lang.ClassNotFoundException: org.drools.workbench.models.guided.template.backend.GuidedRuleTemplateProviderImpl from [Module "deployment.brms-coolstore-demo.war:main" from Service Module Loader]
09:50:20,459 ERROR [stderr] (Timer-2) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
09:50:20,460 ERROR [stderr] (Timer-2) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
09:50:20,460 ERROR [stderr] (Timer-2) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
09:50:20,460 ERROR [stderr] (Timer-2) 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
09:50:20,460 ERROR [stderr] (Timer-2) 	at java.lang.Class.forName0(Native Method)
09:50:20,460 ERROR [stderr] (Timer-2) 	at java.lang.Class.forName(Class.java:264)
09:50:20,460 ERROR [stderr] (Timer-2) 	at org.kie.internal.utils.ServiceRegistryImpl$ReflectionInstantiator.newInstance(ServiceRegistryImpl.java:270)
09:50:20,460 ERROR [stderr] (Timer-2) 	... 20 more

**Comment by hucmaggie** [comment]
Retried it after cleaning up my /tmp/maven-repo and issue could not be reproduced.
